backend:
  # name: github
  # repo: damourChris/fossil-logging
  # branch: main # Branch to update (optional; defaults to master)
  name: test-repo

media_folder: static/img
public_folder: /img

collections:
  - name: "fossils"
    label: "Fossil"
    folder: "content/fossils"
    format: "json"
    slug: "{{name}}-{{date}}"
    create: true
    editor:
      preview: true
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
        required: false
      - label: "Classification"
        name: "classification"
        widget: "object"
        fields:
          - Domains:
            label: "Domain"
            name: "domain"
            widget: "string"
          - label: "Kingdom"
            name: "kingdom"
            widget: "string"
          - label: "Phylum"
            name: "phylum"
            widget: "string"
          - label: "Class"
            name: "class"
            widget: "string"
            required: false
          - label: "Order"
            name: "order"
            widget: "string"
            required: false
          - label: "Family"
            name: "family"
            widget: "string"
            required: false
          - label: "Genus"
            name: "genus"
            widget: "string"
            required: false
          - label: "Species"
            name: "species"
            widget: "string"
            required: false
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        required: false
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
  - name: "collections"
    label: "Collection"
    folder: "content/collections"
    format: "json"
    create: true
    slug: "{{name}}"
    editor:
      preview: true
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Location"
        name: "location"
        widget: "map"
        required: false
      - label: "Description"
        name: "description"
        widget: "string"
        required: false
      - label: "Fossils"
        name: "fossils"
        widget: "list"
        fields:
          - label: "Fossil"
            name: "name"
            widget: "relation"
            value_field: "name"
            collection: "fossils"
            search_fields:
              [
                "name",
                "classification.domain",
                "classification.kingdom",
                "classification.phylum",
                "classification.class",
                "classification.order",
                "classification.family",
                "classification.genus",
                "classification.species",
              ]
          - label: "Occurrence"
            name: "occurence"
            widget: "number"
          - label: "Tags"
            name: "tags"
            widget: "list"
            fields:
              - label: "Tag"
                name: "tag"
                widget: "string"
